services:
  reprpoc.api:
    image: ${DOCKER_REGISTRY-}reprpocapi
    ports:
        - "53333:8080"
        - "53334:8081"
    build:
      context: .
      dockerfile: REPRPoc.Api/Dockerfile

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
